---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: soutenance21
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soutenance21-app
      version: blue
  template:
    metadata:
      name: soutenance21-pod
      labels:
        app: soutenance21-app
        version: blue
    spec:
      containers:
      - name: soutenance21-container
        image: hbzone/soutenance21_hbz:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service 
metadata:
  name: soutenance21-svc
  labels:
    app: soutenance21-app
spec:
  selector:
    app: soutenance21-app
    version: blue
  type: NodePort
  ports:
  - nodePort: 31113
    port: 80
    targetPort: 80
